// <auto-generated />
namespace Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddIntegrationStatusType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIntegrationStatusType));
        
        string IMigrationMetadata.Id
        {
            get { return "201601251938233_AddIntegrationStatusType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
